#!/usr/bin/env bash

# kye
# 2014.06.03
# 2014.06.23

# functions {

# waxon {
function waxon {

	# ${@} calling command

	# vars {
	local dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	local src="${dir}/src"
	local modules="${dir}/modules"
	local logfile="${src}/wax.log"
	# }

	# run tests {
	source ${src}/ensure/notRoot
	source ${src}/ensure/notSubshell
	# }

	# source all the things {
	source ${src}/styles
	source ${src}/icons
	source ${src}/loggers
	# }

	printf "$(date "+%Y.%m.%d %H:%M:%S") - wax ${*}\n" >> ${logfile}
	printf "\n${sul}${sfy}${iwax4} wax on: ${@}${srs}\n\n"

	alias wax="action"

	action "${@}"
	waxoff ${?}

}
# }

# action {
function action {

	# ${1} instruction
	# ${2} module
	# ${@:3} other, passed to instruction

	# run tests {
	source ${src}/ensure/instructionProvided || return 1
	source ${src}/ensure/moduleProvided      || return 1
	source ${src}/ensure/moduleExists        || return 1
	source ${src}/ensure/instructionsExist   || return 1
	source ${modules}/${2}/instructions.sh   || return 1
	source ${src}/ensure/instructionExists   || return 1
	# }

	# vars {
	local me=".wax/modules/${2}"
	# }

	# run module instructions {
	${1} "${@:3}"
	return ${?}
	# }

}
# }

# waxoff {
function waxoff {

	# ${1} status code

	printf "$(date "+%Y.%m.%d %H:%M:%S") - end\n\n" >> ${logfile}
	printf "\n${sul}${sfy}"
	test "${1}" -eq 0 && printf "${iwax4}" || printf "${iwax6}"
	printf " wax off${srs}\n\n"

}
# }

# }

# wax {
waxon "${@}"
# }

# finish {
unset -f waxon
unset -f action
unset -f waxoff
source ${HOME}/.bashrc
# }
